### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sansSpoon** [ria-com/node-koajs-rest-skeleton#12]
I'd just like to say, Thanks! Out of all the templates, examples, and other rubbish, I found this repository to be the best example of how a Koa@2 application can be put together.

Thanks again!

**Comment by ApelSYN** [comment]
You are welcome :)

**Comment by trofivan** [comment]
@ApelSYN спасибо за репозиторий. 
А как вы делаете фильтрацию GET запроса (например пагинацию). Query string или ещё какие-то практики?
С фронта комбинируете запросы и всю логику реализуете на клиенте?
